### ISSUE TITLE
Controllerのリファクタリング

### ISSUE THREAD

**Issue by toyokappa** [toyokappa/knowledge-stocker#17]

**Comment by yhirano55** [comment]
## 修正箇所

下記、1つのPRにまとめずに、分割してPR作った方がよさそうです。どの順番で対応してもよいです。

1. ApplicationControllerにSessionsHelperを挿すのをやめる

    ```ruby
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception
      include SessionsHelper

      def logged_in_user
        unless logged_in?
          flash[:danger] = "ログインしてください"
          redirect_to login_url
        end
      end
    end
    ```

    - HelperはViewのために存在するので、Controllerの処理を書かない方がよい。
    - そもそもModuleは、複数のClass間で処理を共通化させるために使うもの。
    - ここでは分けるメリットがなさそう。
    - Controllerで定義したメソッドを、viewで利用する場合、helper_methodというマクロが存在する。ただし、必要最小限に使うのがよさそう。
    - Helperも必要最小限に使うのがよさそう。

2. 認証を利用するシステムの場合、ホワイトリスト（only）ではなく、ブラックリスト（except）でログインを要求するのが常

    - WordsControllerのみbefore_actionを設定するのではなくて、ApplicationControllerで、ログインを要求するbefore_actionを定義した方がよい（理由: ホワイトリストだと対応が漏れる）
    - `logged_in_user` というメソッド名からは、認証しているかどうかをチェックしているかどうかが想像しにくい。[authenticate](https://github.com/houndci/hound/blob/master/app/controllers/application_controller.rb#L32)  or authenticate_user などがよくある命名です。品詞を意識した方がよい。名詞はgetterを連想させる。

3. current_userのリソースならば、アソシエーションを使用する。

    ```ruby
    class WordsController < ApplicationController
      before_action :logged_in_user

      def index
        # NG
        @words = Word.where(user_id: current_user)
      end
    ```

    - edit, update, destroyの実装を見るに、異なるユーザーのリソースが変更できてしまっている。

4. コントローラーに直接書かれた日本語をI18nに切り出す

5. ログにpassword_confirmationの値が表示されるかどうか目視で確認する。確認できたら、filter_parametersにpassword_confirmationを追加する。

6. URLの再設計

    たぶん、下記のようなことがやりたいんだと思うけど、現状そうなってないので直す。
    知識が薄そうなので、ルーティングに関するRails Guideを読みながら対応する。

    | URL | 内容 |
    |:----|:-----|
    | /users | User 一覧 |
    | /users/:id | User 詳細 |
    | /users/:id/words | 特定 User の Word 一覧 |
    | /users/:id/words/:id | 特定 User の Word 詳細 |

7. ルーティングの修正: 未使用なURLはマッピングしないようにする

    こちらもRailsガイドを読んで、resourcesで定義する方法を学ぶ。 `bin/rails routes` を実行すると定義されたURLの一覧が取得できる。

8. ページネーション対応

    - n 件ずつ表示して、それ以降は次へ、みたいな機能を追加実装する。

---

OSSで公開されている Railsアプリケーション のコードを読んで、知識を深めた方がよさそうです。Railsチュートリアル + Googleで実装している雰囲気が強い。

いきなり全部読むのは不可能かつ不毛なので、ルーティングだけ読む、signin, signupの処理だけ読むなど、テーマを決めるとサクッと読めます。

- https://github.com/kami-zh/repost
- https://github.com/houndci/hound
