### ISSUE TITLE
rubocopを導入する

### ISSUE THREAD

**Issue by toyokappa** [toyokappa/knowledge-stocker#26]

**Comment by yhirano55** [comment]
作業手順は下記です。コミットは全部1つにするとかなり大きくなるので、コミットログを見て、作業手順が分かるよう、適宜分割するとよいと思います。

1. `onkcop` を導入する。
2. onkcopから設定ファイルを生成する。
3. `rails` の設定を有効化する
4. `bundle exec rubocop -a` で自動補正
5. 自動補正できない警告を手動で対応
